ALTER TABLE "admin_tokens" DROP CONSTRAINT IF EXISTS "admin_tokens_admin_id_fkey";
ALTER TABLE "tokens" DROP CONSTRAINT IF EXISTS "tokens_user_id_fkey";
ALTER TABLE "preferences" DROP CONSTRAINT IF EXISTS "preferences_user_id_fkey";
ALTER TABLE "pending_posts" DROP CONSTRAINT IF EXISTS "pending_posts_user_id_fkey";
ALTER TABLE "pending_posts" DROP CONSTRAINT IF EXISTS "pending_posts_community_id_fkey";
ALTER TABLE "reports" DROP CONSTRAINT IF EXISTS "reports_reported_by_fkey";
ALTER TABLE "reports" DROP CONSTRAINT IF EXISTS "reports_community_id_fkey";
ALTER TABLE "reports" DROP CONSTRAINT IF EXISTS "reports_post_id_fkey";
ALTER TABLE "rules" DROP CONSTRAINT IF EXISTS "rules_community_id_fkey";
ALTER TABLE "comments" DROP CONSTRAINT IF EXISTS "comments_post_id_fkey";
ALTER TABLE "comments" DROP CONSTRAINT IF EXISTS "comments_user_id_fkey";
ALTER TABLE "saved_posts" DROP CONSTRAINT IF EXISTS "saved_posts_post_id_fkey";
ALTER TABLE "saved_posts" DROP CONSTRAINT IF EXISTS "saved_posts_user_id_fkey";
ALTER TABLE "post_likes" DROP CONSTRAINT IF EXISTS "post_likes_user_id_fkey";
ALTER TABLE "post_likes" DROP CONSTRAINT IF EXISTS "post_likes_post_id_fkey";
ALTER TABLE "posts" DROP CONSTRAINT IF EXISTS "posts_user_id_fkey";
ALTER TABLE "posts" DROP CONSTRAINT IF EXISTS "posts_community_id_fkey";
ALTER TABLE "community_banned_users" DROP CONSTRAINT IF EXISTS "community_banned_users_user_id_fkey";
ALTER TABLE "community_banned_users" DROP CONSTRAINT IF EXISTS "community_banned_users_ community_id_fkey";
ALTER TABLE "community_members" DROP CONSTRAINT IF EXISTS "community_members_user_id_fkey";
ALTER TABLE "community_members" DROP CONSTRAINT IF EXISTS "community_members_community_id_fkey";
ALTER TABLE "relationships" DROP CONSTRAINT IF EXISTS "relationships_following_id_fkey";
ALTER TABLE "relationships" DROP CONSTRAINT IF EXISTS "relationships_follower_id_fkey";

DROP INDEX IF EXISTS "admins_username_key";
DROP INDEX IF EXISTS "users_email_key";

DROP TABLE IF EXISTS "emails";
DROP TABLE IF EXISTS "configs";
DROP TABLE IF EXISTS "logs";
DROP TABLE IF EXISTS "admin_tokens";
DROP TABLE IF EXISTS "admins";
DROP TABLE IF EXISTS "tokens";
DROP TABLE IF EXISTS "preferences";
DROP TABLE IF EXISTS "suspicious_logins";
DROP TABLE IF EXISTS "pending_posts";
DROP TABLE IF EXISTS "reports";
DROP TABLE IF EXISTS "rules";
DROP TABLE IF EXISTS "comments";
DROP TABLE IF EXISTS "saved_posts";
DROP TABLE IF EXISTS "post_likes";
DROP TABLE IF EXISTS "posts";
DROP TABLE IF EXISTS "community_banned_users";
DROP TABLE IF EXISTS "community_members";
DROP TABLE IF EXISTS "communities";
DROP TABLE IF EXISTS "relationships";
DROP TABLE IF EXISTS "users";
